# Generated by Django 6.1 on 2026-09-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_booking_transportation_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transportation_mode',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='transportation_price',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='accommodation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='meals',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='sightseeing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='transportation',
            field=models.CharField(default='Tourist Bus', max_length=50),
        ),
    ]
