# Generated by Django 6.1 on 2026-09-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_remove_booking_transportation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transportation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='transportation_upgrade',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
